build:
  stage: build
  script:
    - chmod +x run.sh clean.sh
    - bash run.sh
    - docker build -t k8s_dotnet .
    - docker run -d -p 5000:80 --restart unless-stopped k8s_dotnet
    - bash clean.sh
  environment:
    name: staging
    url: http://192.168.137.101:5000